import React from 'react'
import '../index.css'

export default function Buttons() {
    return (
        <div id='buttonContainer'>
            <div id='numberContainer'>
                <button
                    className='startNumberKey'
                    type='button'
                    value='clear'
                    data-keycode='67'>
                    C
                </button>
                <button
                    className='startNumberKey'
                    type='button'
                    value='toggle'
                    data-keycode='84'>
                    +/-
                </button>
                <button
                    className='startNumberKey'
                    type='button'
                    value='mod'
                    data-keycode='88'>
                    %
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='1'
                    data-keycode='49'>
                    1
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='2'
                    data-keycode='50'>
                    2
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='3'
                    data-keycode='51'>
                    3
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='4'
                    data-keycode='52'>
                    4
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='5'
                    data-keycode='53'>
                    5
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='6'
                    data-keycode='54'>
                    6
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='7'
                    data-keycode='55'>
                    7
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='8'
                    data-keycode='56'>
                    8
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='9'
                    data-keycode='57'>
                    9
                </button>
                <button
                    className='ceroNumberKey'
                    type='button'
                    value='0'
                    data-keycode='48'>
                    0
                </button>
                <button
                    className='numberKey'
                    type='button'
                    value='.'
                    data-keycode='190'>
                    .
                </button>
            </div>
            <div id='operatorContainer'>
                <button
                    className='operatorKey'
                    type='button'
                    value='div'
                    data-keycode='47'>
                    ÷
                </button>
                <button
                    className='operatorKey'
                    type='button'
                    value='221'
                    data-keycode='mult'>
                    x
                </button>
                <button
                    className='operatorKey'
                    type='button'
                    value='189'
                    data-keycode='sub'>
                    -
                </button>
                <button
                    className='operatorKey'
                    type='button'
                    value='187'
                    data-keycode='sum'>
                    +
                </button>
                <button
                    className='operatorKey'
                    type='button'
                    value='submit'
                    data-keycode='13'>
                    =
                </button>
            </div>
        </div>
    )
}
